### ISSUE TITLE
Signature char

### ISSUE THREAD

**Issue by PierreOlivierBrillant** [guyfrancoeur/INF3135_A2020#10]
Dans quel(s) contexte(s) est-ce que les signatures des fonctions à tester contenant des char pourraient elles être utilisées selon  les différents types de montres émettant différentes sortes de transactions?

**Comment by guyfrancoeur** [comment]
Bonjour,

Pas certain que nous devrions nous poser cette question en ce moment.
Est-ce un bloquant ?
Peux-tu clarifier svp.

**Comment by PierreOlivierBrillant** [comment]
D'un côté pratique, je me demande quel genre de valeurs la fonction prend, soit des char, mais dans quel contexte, comment est-ce que la plage de valeurs données devrait s'appliquer à des char. D'un côté plus personnel, c'est plus intéressant de comprendre la portée et la raison de ce que j'accomplis, surtout si le contexte pédagogique donné est en lien avec quelque chose de concret.

**Comment by guyfrancoeur** [comment]
Je vais tenter qqc,

Il faut voir le `char` comme une très petit entier.  Donc si vous avez des petites valeurs il est souhaitable de l'utiliser.
