### ISSUE TITLE
Une branche nommée testunitaire sera produite et votre travail sera livré dans cette branche

### ISSUE THREAD

**Issue by EzzeddineAlimi** [guyfrancoeur/INF3135_A2020#13]
Est ce qu'on aura a la fin seulement une branche testunitaire ? donc pas de branch master pour la fin ?

**Comment by guyfrancoeur** [comment]
Bonjour,

master (pour moi) et testunitaire pour votre projet.

Un projet sans branche master ca fonctionne mais pas un bonne idée.  Moi je vais l'utiliser si elle est présente.
