### ISSUE TITLE
Invitation au repository annulée?

### ISSUE THREAD

**Issue by PierreOlivierBrillant** [guyfrancoeur/INF3135_A2020#15]
Salut! En consultant l'onglet "Manage Access" sur le repository de mon projet, j'ai remarqué que l'invitation pour votre utilisateur semble avoir disparue. Est-ce normal?

**Comment by guyfrancoeur** [comment]
Bonsoir PO,

Refaire si c'est le cas.
Je ne sais pas quelles sont les politiques GitHub à ce sujet.

Aucun souci.  L'automate va vous re-ajouter éventuellement.

G

**Comment by opdelta** [comment]
Même chose pour moi! Mon dépot ne figurait pas dans la liste de votre repertoire. Je vous ai envoyé une nouvelle demande de collaboration.
