### ISSUE TITLE
branch master

### ISSUE THREAD

**Issue by TarekElTayeh** [guyfrancoeur/INF3135_A2020#16]
Bonsoir Mr. Francoeur, 

Est ce que la branch `master` doit etre completement vide ? Car j'ai fait le switch a la branch `testunitaire` a la derniere minute et tous les fichiers se situent dans les 2 branches.

**Comment by guyfrancoeur** [comment]
Allo Tarek,

Pas grave. En autant quelle (branche master) existe (default).

la branche importante c'est `testunitaire`.

Je ne regarde pas le contenu de cette branche master.
Idéalement vide. Vous pouvez la vider ou faire le menage.

NOTE : Faites le TP avant.

G
