### ISSUE TITLE
erreur 1 

### ISSUE THREAD

**Issue by shanieUQAM** [guyfrancoeur/INF3135_A2020#17]
Bon soir, 

Est-ce que l'erreur 1, le droit d'écriture peut être régler par les paramètres de github? ou par les droits de fichiers peut-être?

Merci

**Comment by guyfrancoeur** [comment]
Bonsoir Shanie,

Ai-je les droits (collaboration) sur le `dépôt` ?

Je vais vérifier et mettre a jour le post si je trouve qqc. voir https://github.com/guyfrancoeur/INF3135_A2020/issues/17#issuecomment-711478097

G

**Comment by my-linh-luu** [comment]
J'ai la même erreur que Shanie. J'ai vérifié les settings, tout est beau et vous êtes collaborateur. Par contre, mon default branch est `main` et non pas `master`. Est-ce que cela pourrait être la cause du problème?

**Comment by shanieUQAM** [comment]
Moi aussi mon default est `main` et non `master`.

D'ailleurs, [Droit des utilisateurs](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository) dit "Note: In a private repository, repository owners can only grant write access to collaborators. Collaborators can't have read-only access to repositories owned by a user account."

**Comment by guyfrancoeur** [comment]
Bonsoir, 

Trouvé! Votre branche `master` est surement nommé `main` (default).

Ce n'est pas grave.  Nouveau standard de GitHub depuis qq jours.

Aucun souci pas de point (ou perte de point) pour ceci.
Le seul trouble ce sera les fichiers de commentaires risque de ne pas ce rendre.

G

**Comment by my-linh-luu** [comment]
Donc pas de commentaires pour la correction? :(

**Comment by shanieUQAM** [comment]
Merci M. Francoeur! 

Et à titre d'information, il n'a pas manière de changer le `main` pour `master`?

**Comment by guyfrancoeur** [comment]
Allo,

Je vais surement fixé (mes scripts) ça bientôt. Pour travailler avec `main` au lieu de `master`. 
Lorsque le temps le permet.

Je peux aussi écrire, mes commentaires, dans la branche `testunitaire`.

 Allez dormir!

G
