### ISSUE TITLE
Erreur de nom de fichier, que faire ?

### ISSUE THREAD

**Issue by JulesHauchecorne** [guyfrancoeur/INF3135_A2020#18]
J'ai remarqué dans le log que mon list.sh n'a pas été lu parce qu'il fallait le nommer liste.sh. Je me demande s'il serait possible de le corriger quand même.

**Comment by guyfrancoeur** [comment]
Oui fait vite! avant 23h59 svp.

**Comment by JulesHauchecorne** [comment]
je l'ai fait

**Comment by JulesHauchecorne** [comment]
merci beaucoup
