### ISSUE TITLE
TP2 : tp1.zip ou tp2.zip. Prendre tp2.zip si présent sinon tp1.zip

### ISSUE THREAD

**Issue by saledemon** [guyfrancoeur/INF3135_A2020#21]
Plusieurs questions à propos du tp2 ;

Premièrement, il est dit qu'il faut utiliser les fonctions contenues dans tp2.zip. Or, je ne trouve pas ce fichier dans le répertoire.

Deuxièmement, à quoi servent les fichiers malib.h et malib.c. Il n'est mention de ces fichiers qu'à la fin du descriptif du tp et on ne dit ce qu'ils doivent faire...? Que signifie, dans les critères, "avec la détection des inclusions multiples" ?

Troisièmement (c'est probablement en lien avec ma première question), aurons-nous accès à un corrigé du tp1 pour être certain que nous avons repéré les fonctions qui étaient vraiment valides (ou peut-être que cela se réglera avec l'apparition des nouveaux tcv.h et tcv.o).

Merci:)

**Comment by guyfrancoeur** [comment]
Bonjour,

- Le tp2.zip sera disponible seulement si nécessaire.  Prendre le fichier tp1.zip pour l'instant. Vous savez comment gérer cela.

- Nous allons voir ces notions en détails dans pas long. Dans le Chapitre 9. Le prochain surement.

- À venir, mais surement.

Merci

**Comment by saledemon** [comment]
Je ne comprends pas trop le concept de "si nécessaire"... J'ai sûrement fait quelque chose de mal dans le tp1 puisque pour moi il n'y avait que deux fonctions valides au final.. ? Ça ne marchera pas avec le tp2 si c'est le cas..

**Comment by guyfrancoeur** [comment]
Allo,

Je ne ferai surement pas un fichier pour aucune raison.  Pourquoi changer ce qui fonctionne?

Si je fais des changements (correctif ou ajout) dans le .h et .c ---> .o il y aura un fichier zip qui sera rendu disponible.

NOTE ce sujet a été clairement mentionné en classe.  Je suis étonné de le revoir ici.

G

**Comment by saledemon** [comment]
Daccord... Donc si je comprends bien, puisque je n'ai pas bien compris le tp1, je serai pénalisé pour le tp2 puisque je n'ai aucune certitude d'avoir un corrigé pour m'aider a comprendre mes erreurs ?

**Comment by patlenew** [comment]
Si je me trompe pas, je pense qu'il veut dire qu'il n'a pas à uploader un fichier tp2.zip car le fichier tp1.zip contient déjà ce qu'on a de besoin pour l'instant (genre les fonctions à testés, la version), et que le fichier tp2.zip contiendrait la même chose, il va juste faire un fichier tp2.zip si il doit changé quelque chose dans tcv.h/tcv.o, si jamais ça peut clarifier
