### ISSUE TITLE
TP2 : SUJET svp. et ne pas mixer les sujets dans un meme topic.

### ISSUE THREAD

**Issue by MaelPJoly** [guyfrancoeur/INF3135_A2020#22]
Bonjour,

Première question, peut-on créé un fichier pour stocker les informations provenants des commandes faites au main pour pouvoir les réutilisées plus tard? Par exemple, dans votre exemple, il y a les trois commandes suivantes en entrée:

2 01 38.2
10020 02 -10.2
11112 03 157
Et en sortie il y a 

21 38.2 -10.2 157

Donc une température ambiante, une température humaine et une pulsation sont entrées, puis plus tard réafficher sur la même ligne. Il faut donc avoir un moyen pour stocker tous les informations entré  par le stdin pour ensuite les réafficher à la console.

Deuxièmement, à quelle fréquence faut-il afficher les sorties? À chaque fois qu’est fait un appel du programme(donc après chaque ligne entrée au terminal)? Ou était-ce avec une autre fréquence?

Merci.

**Comment by LMGsean** [comment]
Salut !

Pour répondre à ta deuxième question, selon moi, il faudrait afficher les sorties après avoir TOUT reçu les entrées (si je me fie à son exemple d'entrée et de sortie du programme). Par contre, je crois que nous devrions afficher les sorties en ordre des transactions en entrée.

Pour ta première question, je crois que c'est possible, car dans la section "Description du travail", le output de la commande "cat file.dat" est redirigé vers l'exécutable.

$ cat file.dat | ./tp2

Sinon, je me pose la question suivante:
Pour passer nos paramètres, sommes-nous libre de choisir comment passer les arguments à l'exécutable ou devons-nous être en mesure de tous les exécutés selon les différentes syntaxes décrites dans l'énoncé (i.e Tous les respecter)?

**Comment by guyfrancoeur** [comment]
Bonjour

@MaelPJoly 

1. Oui tu peux faire des fichiers (qui simule les trx reçus) pour t'aider à réaliser le tp2.  Très bonne idée! Il est souhaitable de procéder ainsi.
2. Il faut afficher au fur et à mesure.  Il n'y a pas assez de mémoire dans la pastille/puce pour maintenir des buffers.

@LMGsean Ta deuxième phrase est exacte.

1. Il n'y a pas d'arguments pour ce programme, `tp2`.

**Comment by MaelPJoly** [comment]
Bonjour,

Pour les moyennes de TA, TH et pulsation ainsi que leur cumul d'erreur, est-ce c'est l'ensemble des données entrées dans le programme qui sont considérées pour faire ces calculs menant à une seule réponse 21, 22 et 23 pour la globalité, ou on doit un faire calcul différent pour chaque id différent entré et donc avoir plusieurs réponse 21, 22 et 23?

**Comment by Patrickcob** [comment]
Si j'ai bien compris, on produit une transaction de sortie en fonction de la bonne transaction d'entrée immédiatement, afin de créer une forme de relation immédiatement entre la capsule et l'information traité. De cette façon, une app pourrait immédiatement agir. Seulement lorsque la stdin est terminé, on "publie" les transactions 21 à 23? Mise à part les trois dernières, on procède en temps réel?

**Comment by gabrielrose1** [comment]
@Patrickcob Va relire les exemples visuels dans l'énoncé ainsi que la section des transactions en sortie je crois que tu vas pouvoir y trouver la réponse à ton hypothèse sinon je ne suis pas sur qu'il est permit de répondre à ta question

**Comment by Patrickcob** [comment]
>  Certaines transactions en entrées vont nécessairement provoquer une sortie.

Je crois que ça répond en effet à ma question!
