### ISSUE TITLE
TP2 : Question

### ISSUE THREAD

**Issue by awahabbaga** [guyfrancoeur/INF3135_A2020#24]
Bonsoir,

Les fichiers malib.c et malib.h nous serons fournis ou devons nous les créer nous même?
Si nous devons les créer où interviennent-ils dans le TP ?

Merci.

**Comment by guyfrancoeur** [comment]
Bonjour,

1- Vous devez les créer.
2- Ceci est une demande de réponse je ne peux pas répondre.

G

**Comment by nineyalexandre** [comment]
Bonjour awahabbaga,

Sans y apporter de solution , si les interactions entre les fichiers malib.c / .h et ton tp2.c ne te sont pas claires, tu peux revoir la structure  de données (ie les piles que nous avons pu faire en labo). Ca te donnera une idée de la structure de ton projet entre ces différents fichiers.
