### ISSUE TITLE
TP2 : comment faire ?

### ISSUE THREAD

**Issue by hakimba1** [guyfrancoeur/INF3135_A2020#25]
Bonjour,

je me demande si  les transactions en entrée qu'on doit lire proviennent d'un fichier ou l'utilisateur pour savoir de quelle façon je procède, je ne demande pas une réponse mais une précision si ce n'est pas le cas alors quand on lance ./tp2 sans données en entrée  le programme devrait nous donner quoi comme résultat .

Merci

**Comment by guyfrancoeur** [comment]
Bonjour,

@Groupe : Vous n'avez pas à répondre à cette question.

@hakimba1 
Quand tu demande si je fais ceci le programme devrait donner quoi ?  C'est exactement ce à quoi tu dois répondre.

1. Tu dois tenter, faire une vérification;
2. Par la suite, (après le test) tu pourras voir, constater ce qui ce passe;
3. Après coup, tu seras en mesure de prendre une décision;

La provenance ou elles arrivent (pas comment) des données est décrite dans l'énoncé.  De plus, je ne crois pas avoir fait usage du mot `utilisateur` dans l'énoncé.

G

**Comment by hakimba1** [comment]
Bonjour,

Merci @guyfrancoeur
