### ISSUE TITLE
TP1 : Commentaires : suite de la correction

### ISSUE THREAD

**Issue by guyfrancoeur** [guyfrancoeur/INF3135_A2020#26]
Bonjour,

Mettre seulement le chapeau qui vous fait.  La perfection existe-t-il y a des **20 sur 20 Bravo !**

Je vais débuter par les **bons** coups : 
- très bons résultats dans l'ensemble.
- le prof a fixé mon dépôt, je suis content, lui fatigué.
- consultez fichier résultats pour en savoir plus. Seulement la dernière correction compte.
- vos branches sont bien.
- cp.txt est présent a 83%  (12 fix) --> 95% complet
  + manque encore 6.

Moins bien : 
- Ne pas vous compliquer la vie svp
- Ne laissez pas le hasard décider
  + toujours tester, vérifier, exécuter deux fois ou plus, à chaque fois
  + comment faites-vous pour savoir que rien n'est brisé après un changement ?
  + travaillez-vous toujours de la même façon ?
- Makefile : 
  + avez-vous assumé un ordre d'exécution ou un état du dépôt local ?
  + quelqu'un de nouveau ne connait pas votre projet, quel est le pourcentage de risque d'erreur ?
  + est-ce que `make clean ; make clean` fonctionne pour vous ?
  + dépendances manquantes
      - la commande `make` utilisé seule est-ce possible de la faire fonctionner ? 
      -  est-ce vraiment nécessaire de faire `make lib` selon vous ?
  + bizarrement certaines commandes demandent des confirmations
  + la commande `wget` génère des poubelles (logs), on ne veut pas cela en production.
      - ceci sera un élément qui sera évalué lors des autres travaux.
- liste.sh
  + Il y a eu un plagiat.  Les concernés vous me devez une explication.
  + vous devez réviser `stdin` et `stdout`.
  + vous devez réviser `bash`.
  + vous devez simplifier si possible.

Svp réagissez à ce post. Cela m'aide pour savoir qui a lu.

Bravo on lâche pas vous êtes bon, vous êtes en route vers la perfection, mais qui est parfait ?  
Ce sera toujours de plus en plus difficile d'être parfait, lorsqu'on se compare avec l'élite.

À la fin je donne UNE LETTRE = {A+,A, ... ,D} à chacun. Les points sont relatifs et votre `lettre finale` est en fonction de votre groupe. Vous pouvez obtenir la plus haute LETTRE même en ayant pas tous les points.

### fichier utilisé pour la correction (exécuté séquetiellement)
```bash
1 00 0 recuperation          echo -e "**** bravo ****" >> ../inf*/commentaires-partie2.txt
1 00 0 completude            test -f tp1.c && test -f .gitignore && test -f cp.txt && test -f liste.sh
1 00 0 Makefile existe       test -f Makefile
0 00 0 preparation make (GF) rm -f tcv.h tcv.o tp1.o tp1
1 00 0 make + dependances    make
1 00 0 verification          test -f tp1
1 10 0 make lib              make lib
1 00 0 verification          test -f tcv.h -a -f tcv.o
1 10 0 make clean            make clean ; make clean
1 10 0 make clean (test)     test ! -f tp1.o && test ! -f tp1 && test ! -d data && test ! -f tcv.o && test ! -f tcv.h && test ! -f ./data/data.zip
1 10 0 README.md             test -f README.md
2 00 0 liste.sh              echo -e "validerPulsation\\nvaliderSignal" | bash liste.sh > t1.guy ; WC=$(wc -l t1.guy) ; test ${WC:0:2} -eq 0
0 10 0 copy lib              cp -f ${HOME}/cours/inf3135/tp1/tcv.[oh] .
1 10 0 compilation           gcc -Wall -Werror=vla -I/usr/include/CUnit -L/usr/lib/x86_64-linux-gnu -o tp1 tp1.c tcv.o -lcunit &> compilation.guy ; test ! -s compilation.guy
1 10 0 compilation (backup)  make
0 00 0 bon header            cp -f ${HOME}/cours/inf3135/tp1/tcv.[oh] .
3 90 0 execution             ./tp1 > /dev/null && ./tp1 | bash liste.sh | sort -u -o fonction.etu
2 00 0 resultats             ${HOME}/depot/compare.sh ./fonction.etu ${HOME}/cours/inf3135/tp1/p4.guy && ${HOME}/depot/compare.sh ${HOME}/cours/inf3135/tp1/p4.guy ./fonction.etu
1 00 0 git ++                echo "*.guy" >> .gitignore ; date > version.txt ; sort -u -o .gitignore .gitignore ; git add version.txt .gitignore fonction.etu && git commit -m "output de tp1+liste.sh est dans fonction.etu" && git push
0 00 0                       echo -e "*** compilation ***" >> ../inf*/commentaires-partie2.txt ; cat compilation.guy >> ../inf*/commentaires-partie2.txt ; echo " " >> ../inf*/commentaires-partie2.txt
0 00 0                       echo -e "***** liste.sh ****" >> ../inf*/commentaires-partie2.txt ; cat fonction.etu >> ../inf*/commentaires-partie2.txt ; echo " " >> ../inf*/commentaires-partie2.txt
0 00 0                       echo -e "Correction fin." >> ../inf*/commentaires-partie2.txt
```

G

**Comment by patlenew** [comment]
Bonjour! 

En fait j'aimerais juste comprendre comment lire le fichier de résultat (resultat-inf3135-a2020-testunitaire.txt) pour comprendre exactement ce qui manquait dans mon projet, si je lis les points de gauche à droite est-ce que ça équivaut à l'ordre dans l'énoncé?

Merci!

**Comment by nineyalexandre** [comment]
Bonjour Guy,

Merci pour le détail de votre script qui permet de voir ~~à peu près~~ précisément où nous n’avons pas eu le point ~~potentiellement perdu des points~~.

Néanmoins, je ne saisis personnellement pas pourquoi ces points ont été perdus dans les différents sujets évoqués (make lib, résultats, make clean test, make backup). J'ai beau refaire mes exécutions qui me semblent bonnes, j'ai besoin de précisions quant à vos attentes par rapport à ce que j ai fourni.

par GF 😁
> > Vu que je suis persévérant et qu'en plus je suis intelligent je vais tenter différentes façons. Vous avez déjà évoqué `R = D C I`, je vais l'appliquer avec les connaissances acquises cette session. Je vais surtout m'assurer que mes livrables sont conformes à l'énoncé et aux résultats formelles (output) attendus. Nous ne sommes pas en art plastique après tout, hein... Un peu de formalisme et conformité pour les `entrées` et les `sorties` c'est utile en informatique.

Vous en remerciant par avance,

Alexandre
