### ISSUE TITLE
TP2 : pulsations float vs size_t

### ISSUE THREAD

**Issue by fethiuqam** [guyfrancoeur/INF3135_A2020#27]
Bonjour,
ma question concerne le type de pulsations car à l'entrée (lecture) c'est un float :

03: Pulsation par minute
Définition : <timestamp> 03 <pulsation par minute | ERREUR>
Signature : <size_t> 03 <**float**|ERROR>

alors qu'en sortie , son type est size_t : 

21: Moyenne TH TA pulsation erreur
Définition : 21 <la moyenne des TH> <la moyenne des TA> <la moyenne des pulsations>
Signature : 21 <float> <float> <**size_t**>

**Comment by guyfrancoeur** [comment]
Bonjour,

trx 03 : une décision que j'ai prise pour simplifier, le format est comme parreil (langage ado) trx 01 et trx 02.

trx 21 : ça veut dire relache (drop) les décimales. 😎
