### ISSUE TITLE
Énoncé TP2 - Lien du tp2.zip

### ISSUE THREAD

**Issue by Patrickcob** [guyfrancoeur/INF3135_A2020#28]
Bonjour Guy,

`https://github.com/guyfrancoeur/INF3135_A2020/raw/master/tp/tp2.zip` ne semble pas fonctionner actuellement selon le lien dans l'énoncé du tp2.

**Comment by hakimba1** [comment]
Bonjour, 
tu peux utiliser tp1.zip il contient les fichiers nécessaires.

**Comment by nineyalexandre** [comment]
Un tp2.zip sera potentiellement fourni si d'éventuelles corrections seront apportées au programme tcv. Il faut pour l'instant partir du constat que la référence reste tp1.zip.

**Comment by Patrickcob** [comment]
C'est vrai merci! on avait eu effectivement un issue plus tôt là dessus justement!
