### ISSUE TITLE
TP2 : ...

### ISSUE THREAD

**Issue by jeanlouisdicka** [guyfrancoeur/INF3135_A2020#29]
@guyfrancoeur 
Que signifie "erreur" dans les transactions de sortie 21; 22;23?
 Merci

**Comment by davidadjele** [comment]
Bonjour,

@jeanlouisdicka en espérant que ça t'aide, je te suggère de relire la section `Rôle de votre programme` de l'énoncé pour avoir plus d'infos sur le mot `ERREUR` et aussi revoir les définitions des transactions `22` `23`.

**Comment by Nami-R2301** [comment]
@jeanlouisdicka 

Relit ce passage dans l'énoncé pour comprendre mieux à propos des transactions en entrées : 

**Si un capteur donne le mot ERREUR, vous devez réagir à la troisième manifestation du mot ERREUR;
Vous ajoutez un (1) au compteur cumul des mots ERREUR par type;
voir transaction 23.**
