### ISSUE TITLE
TP1 : belle recherche et réflexion, je suis fier de vous. Pas toujours facile, BRAVO!

### ISSUE THREAD

**Issue by guyfrancoeur** [guyfrancoeur/INF3135_A2020#30]
Bonsoir monsieur,

J’ai révisé mes erreurs pour mon tp1 et il m’en reste une seule que je ne suis pas parvenu à réparer.
En fait, je ne suis pas certain quelle est la raison pour laquelle j’ai eu une erreur. 

#### Affirmation
Voici la ligne de l’erreur en question : 
1 00 0 git ++   echo "*.guy" >> .gitignore ; date > version.txt ; sort -u -o .gitignore .gitignore ; git add version.txt .gitignore fonction.etu && git commit -m "output de tp1+liste.sh est dans fonction.etu" && git push
En analysant la ligne, je crois comprendre que je serais supposé avoir un fichier version.txt dans mon répertoire git, mais je n’en ai pas. Est-ce que l’erreur est reliée à cela?

> > par `GF`
> > Si `version.txt` n’est pas présent dans votre dépôt distant, il y eut erreur de push.
> >
> > D'après moi, sans avoir investigué, le git add semble poser problème.
> >
> > SVP regarder le .gitignore.

#### Affirmation
Ou encore, j’ai fait une erreur dans mon fichier liste.sh, il ne recevait pas du `stdin` mais plutôt d’un fichier texte. Ainsi, le fichier fonction.etu est vide. L’erreur serait-elle reliée à cela plutôt? 

> > par `GF`
> >Je penche plus pour un problème de .gitignore pour l'instant.
> >
> > Il est certain que si `liste.sh` n’est pas fonctionnel, alors `fonction.etu` sera vide.  
> >
> > Ceci dit, si `fonction.etu` est **vide**, toujours d'après moi, ne serait pas la cause d'un problème de `git add`, `git push`.

Merci, belle recherche et réflexion .. BRAVO.

GF

Réagissez à ce post.

**Comment by LikensonD** [comment]
Affirmation 1: si le fichier version.txt n existe pas , la commande le crée sinon est elles est écrasé, donc le problème ne vient pas la
