### ISSUE TITLE
TP1: Grille de correction manquante

### ISSUE THREAD

**Issue by PierreOlivierBrillant** [guyfrancoeur/INF3135_A2020#31]
Bonjour, bien que j'ai reçu ma note sur le portail (de 75%), dans mon répertoire personnel la grille de correction du TP1 semble absente. Est-ce normal?

**Comment by PedroLuisBernardos** [comment]
Regarde dans ta branche test unitaire!

**Comment by PierreOlivierBrillant** [comment]
Il y a 2 commit de Guy dans ma branche testunitaire, un qui modifie cp.txt et l'autre qui modifie .gitignore. J'ai l'impression que ce n'est pas le comportement souhaité par le script de correction.

**Comment by PedroLuisBernardos** [comment]
_resultat-inf3135-a2020-testunitaire.txt_
Tu n'as pas ce fichier dans ta branche testunitaire? C'est là qu'il y a les notes

**Comment by PierreOlivierBrillant** [comment]
Je crois pas, non.

![image](https://user-images.githubusercontent.com/19349898/98722605-4287e680-235f-11eb-8ed0-e1ffdf67fa57.png)

**Comment by guyfrancoeur** [comment]
Bonjour PO,

il y a eu une erreur de push (surement)
vérifier le .gitignore (*.txt) ?

G

**Comment by PierreOlivierBrillant** [comment]
Salut Guy, est-ce que c'est possible de réessayer? J'ai modifié mon .gitignore pour ne pas ignorer les fichiers .txt

**Comment by guyfrancoeur** [comment]
Allo,

Je vais tenter un push...    Ca c'est de l'amour ou du service ? 🤪

FAIT!
