### ISSUE TITLE
TPx : erreur lors d'un affichage avec size_t

### ISSUE THREAD

**Issue by Nana-Ousmane** [guyfrancoeur/INF3135_A2020#33]
@guyfrancoeur  j'ai cette erreur lorsque je printf  le timestamp de type size_t :
48: warning: format specifies type 'size_t *' (aka 'unsigned long *') but the argument has type 'size_t'
      (aka 'unsigned long') [-Wformat]
Ce qui est curieux c'est que J'ai d'autres variable du meme type et elles s'affichent sans problème. Est ce que ça serait possible de regarder ça svp? Merci d'avance

**Comment by opdelta** [comment]
Est-ce-que ton printf est bien du type unsigned long ou est-ce-que tu as mis un autre type dedans par inadvertance? (%lu)

**Comment by guyfrancoeur** [comment]
Bonjour,

Il est certain que tu peux regarder cela bien sûr. J'ajoute ceci à la bonne suggestion de @opdelta : 

 > > format specifies type 'size_t *'

Il y a une étoile dans le message.  😲 
Donc, il n'y a pas correspondance de type entre le remplacé et le remplaçant (% et la variable).

G

**Comment by Nana-Ousmane** [comment]
Merci pour vos interventions. J'ai résolu le problème .
