### ISSUE TITLE
TP2 : version et noms des fonctions à utiliser.

### ISSUE THREAD

**Issue by guyfrancoeur** [guyfrancoeur/INF3135_A2020#34]
Bonjour,

La liste des fonctions à utiliser est en fonction de la version de la bibliothèque : 

pour la version : `0.1.1003` et moins : 
```
validerPulsation_3
validerSignal_2
validerTA_3
validerTH_1
```

pour la version : `0.1.1005` @ `0.1.1008` : 
```
validerPulsation_1
validerSignal_3
validerTA_1
validerTH_1
```

Votre programme doit tenir compte des limitations la bibliotheque et fonctionner dans les limites des types de celle-ci.

Réagisez à ce post avec des émoicons, si le coeur vous en dit.

G

**Comment by guillaumetb** [comment]
Est-ce que la fonction ```getVersion``` a été construite comme cela pour des raisons pédagogiques ou est-ce plus efface de procéder ainsi? Je poses la question parce que mon premier réflexe dans l'implémentation d'une fonction ```get``` aurait été de retourner une valeur (ou un pointeur dans ce cas-ci) et non de faire une fonction ```void```.

**Comment by fethiuqam** [comment]
si la version : 0.1.1004 existe , on utilisera quelles fonctions ??

**Comment by tcylia** [comment]
@fethiuqam selon mes tests, ce n'est que les versions que Guy a mentionner qui existent (pour le moment), donc ne te complique pas la vie :P

**Comment by guyfrancoeur** [comment]
Allo tout le monde,

Merci pour ta question @guillaumetb, si tu en veux plus on en reparle en classe.

Mais essentiellement le but est une déclaration adéquate de la variable qui a motivé le void.
Par souci de simplicité. 😉 Facilité d'intégration.

G

**Comment by nickthivierge** [comment]
Bonjour, je constate que dans l'exemple de sortie présent dans l'énoncée nous avons : 
version #: 0.1.10005
Or, il est dit plus haut que nous traitons les versions 0.1.1003 et moins et les versions 0.1.1005 @ 0.1.1008.
Est-ce juste d'assumer qu'il y a une faute de frappe et que la version devrait être:
version #: 0.1.1005
?

**Comment by EzzeddineAlimi** [comment]
est ce qu'on peur avoir des exmples d'entree et de sortie différent pour faire les tests et confirmé que notre programme marche bien ?

**Comment by victoriamorisset** [comment]
> Bonjour, je constate que dans l'exemple de sortie présent dans l'énoncée nous avons :
> version #: 0.1.10005
> Or, il est dit plus haut que nous traitons les versions 0.1.1003 et moins et les versions 0.1.1005 @ 0.1.1008.
> Est-ce juste d'assumer qu'il y a une faute de frappe et que la version devrait être:
> version #: 0.1.1005
> ?

Si on a pas d'indications pour une version plus récente que 0.1.1008 (dans ce cas 0.1.10005), on ne peut pas savoir quelles sont ses limites et donc notre programme ne peut pas en tenir compte, ce qui vient contredire l'énoncé plus haut ("Votre programme doit tenir compte des limitations la bibliotheque et fonctionner dans les limites des types de celle-ci"). Je pense donc que le 0.1.10005 est une faute de frappe.

**Comment by guyfrancoeur** [comment]
Bonjour, 

@EzzeddineAlimi Oui tu peux surement en préparer pour tes besoins.

G
