### ISSUE TITLE
TP2: Transaction 15

### ISSUE THREAD

**Issue by tcylia** [guyfrancoeur/INF3135_A2020#38]
Bonjour ! Je me demandais pour la transaction 15, s'il fallais imprimer l'ordre sequentiel des idPN entrées ou bien,  les trier selon leur valeur et les afficher?
Par exemple , si on a en entrée: 
00 00 1000 3
...
17599 04 1929298
18000 04 1929290
18001  04 1929292
18002 05 1929292 100123 100987 

Est-ce que la sortie devra être: 
15 18002 1000 1929290 1929292 1929298 ?

 Merci !

**Comment by louizette** [comment]
Bonjour, je pense que l'ordre n'est pas important vu qu'ils sont tous des ID de  premier niveau.

**Comment by patlenew** [comment]
Personnellement je n'essayerais pas de supposé quoi que ce soit, et de juste les montrés dans l'ordre que tu les as reçu

**Comment by LMGsean** [comment]
Salut, je crois qu'il faut seulement les afficher dans l'ordre qu'on les reçoit aussi, si je me fie à son exemple d'affichage. De plus, je crois que Francoeur avait mentionné qu'il ne voulait pas qu'on se complique la vie !

**Comment by MaelPJoly** [comment]
Effectivement, pour appuyer ce qui a été dit précédemment, si le professeur s'attendait à ce que l'on trie les ID selon leur valeur, il l'aurait surment mentionné dans l'énoncé.

**Comment by tcylia** [comment]
Merci les amis

**Comment by tcylia** [comment]
Ok just to be sure.. merci les amis
