### ISSUE TITLE
TP2 : math.h

### ISSUE THREAD

**Issue by patlenew** [guyfrancoeur/INF3135_A2020#39]
Bonjour!

Est-ce qu'on a le droit d'utilisé la librairie math.h, vu que techniquement elle est la librairie standard en C pour les maths,

Merci!

**Comment by Nana-Ousmane** [comment]
Oui on a le droit, J'ai posé la question au prof hier.

**Comment by ZZ906** [comment]
oui toute librairie standard (Il y en a une trentaine)
