### ISSUE TITLE
TPx : Fichiers tests et autres fichiers extras.

### ISSUE THREAD

**Issue by Jrobill4rd** [guyfrancoeur/INF3135_A2020#41]
Bonjour Guy,

Est-ce qu'il est mieu d'exclure nos fichiers de tests fonctionnels du dépot distant?

Jeffrey

**Comment by guyfrancoeur** [comment]
Bonjour,

Non, ce n'est pas nécessaire.  Et ce n'est pas souhaitable.
Vous ne voulez pas risquer de perdre des fichiers qui pourraient être utiles.
Je ne regarde pas les extras (fichiers ou autres).

Seul petit hic, assurez-vous qu'un extra ne cause pas un bloquant pour un requis.

Il existe plusieurs moyens afin de proteger ou maintenir vos fichiers dans le dépôt distant.
 - comme une branche distinct.

mais pour les besoins de ce cours, simple est préférable.

G

**Comment by Jrobill4rd** [comment]
Merci beaucoup !

Jeffrey
