### ISSUE TITLE
TP2 : librairie math.h

### ISSUE THREAD

**Issue by louizette** [guyfrancoeur/INF3135_A2020#42]
bonjour à tous,
pour calculer la puissance est ce qu'on a le droit d'utiliser la librairie math.h  ?
je viens de voir qu'une meme question a déjà été posée dans l'issue

**Comment by Mouad-Latif** [comment]
https://github.com/guyfrancoeur/INF3135_A2020/issues/39

**Comment by MaelPJoly** [comment]
Cette question à été adressée au dernier cours, oui on a le droit d'utiliser la librairie math.h puisque c'est une librarie standard.

Pour plus d'informations sur les librairies standards:
http://www.cplusplus.com/reference/clibrary/

**Comment by guyfrancoeur** [comment]
Bonjour,

Cette question est déjà dans les posts fermés. #39 
La question est aussi dans l'énoncé textuellement.

G
