### ISSUE TITLE
TP2 : Valeurs inacceptables: puissance de l'émetteur

### ISSUE THREAD

**Issue by PedroLuisBernardos** [guyfrancoeur/INF3135_A2020#43]
Bonjour!

Je me demandais si on assumait que les valeurs de la puissance de l'émetteur seront toujours `{ 2, 3, 4 }` ?

Ou on assume qu'il peut y avoir des valeurs inacceptables ? Si oui, que fait-on avec le calcul de la distance ?

**Comment by saledemon** [comment]
Je me permets de répondre parce le prof m'avait répondu pendant un cours.. en gros oui, on assume que les puissances seront toujours 2, 3 ou 4. Pas besoin de gérer des erreurs

**Comment by guyfrancoeur** [comment]
Bonjour,

Si ceci est quelque chose de traitable par votre programme vaut mieux le gérer.

**Assumer** : pas très enligné avec les régles (lois) du langage C.

L'énoncé est clair a ce sujet.

G
