### ISSUE TITLE
TP2 : traitement d'une erreur en lien avec le signal RSSI

### ISSUE THREAD

**Issue by saledemon** [guyfrancoeur/INF3135_A2020#44]
Allo, dans la transaction 22, on indique le compte d'erreurs de TA, TH et des Pulsations. Il n'est jamais question des erreurs de signal RSSI. Je sais bien que c'est une question interdite, mais qu'est-ce qu'on est censé faire lorsqu'il y a une erreur de signal ? L'ignorer ?

**Comment by PedroLuisBernardos** [comment]
Ces trois évènements sont pour les erreurs de type ou le mot ERREUR dans les évènements `01 02 03`:
```
21 <la moyenne des TH> <la moyenne des TA> <la moyenne des pulsations>
22 <compteur valeur invalide pour TH> <compteur valeur invalide pour TA> <compteur valeur invalide pour pulsations>
23 <cumul pour TH> <cumul pour TA> <cumul pour pulsations>
```

Il n'y a rien d'indiqué dans l'énnoncé sur un traitement des erreurs du Signal et du idPN.

Pour les valeurs manquantes, par exemple si dans le signal RSSI:
`17599 04 -85 1929292`
Si il y a une valeur manquante, donc par exemple:
`17599 04 -85`

La gestion de ce problème sera au TP3 (Guy a dit ça en cours). J'imagine il nous donnera des directives sur quoi faire quand cela arrive.

**Comment by guyfrancoeur** [comment]
Allo,

Pour l'instant je ne crois pas que ceci est un bloquant.  Vous avez assez à faire pour le tp2.

G
