### ISSUE TITLE
TP2 : script.sh

### ISSUE THREAD

**Issue by B-Yan** [guyfrancoeur/INF3135_A2020#45]
Parmis les quatres manieres d'executer le fichier:

```bash
$ ./tp2

$ cat file.dat | ./tp2

$ ./script.sh | ./tp2

$ head -n 100 file.txt | ./tp2
...
```
Le script.sh doit-il:

A. utiliser seulement file.dat
B. utiliser seulement file.txt
C. prioriser file.dat mais en son absence utiliser file.txt
D. prioriser file.txt mais en son absencer utilise file.dat

Merci!

**Comment by patlenew** [comment]
Je pense que le file.txt/file.dat (et juste rien) c'est juste un exemple de comment ton programme peut recevoir la data (c'est-à-dire par l'entrée standard, un fichier qui a déjà toute les lignes comme dans l'exemple dans l'énoncé, etc)

**Comment by guyfrancoeur** [comment]
Bonjour,

Je ne suis pas certain de comprendre je vais tenter : 
 - `script.sh` est un exemple rien a voir avec un livrable à produire;
 - on pourrait penser que `script.sh` est un simulateur (générateur) de transactions.
 - j'ai fourni qq exemples afin de vous aider;
 - l'entrée standard est la seule utilisable la réception des transactions pour l'exécutable `tp2`.

G

**Comment by louizette** [comment]
entrée par fichier genre file.txt est acceptable ?

**Comment by nickthivierge** [comment]
Si je peux me permettre, peu importe la source de l'information (cat fichier .txt, .sh, .dat, echo bla-bla, ...) l'information passe par l'entrée standard grâce au pipe '|'. De ce fait, la source de l'information n'a pas besoin d'être connue puisque le traitement de celle-ci reste le même.
