### ISSUE TITLE
TP2 : Implémentation de structures de données abstraites

### ISSUE THREAD

**Issue by Jeremie-Gour** [guyfrancoeur/INF3135_A2020#46]
Bonjour,

Pour ce qui en est de la partie livrable du travail, est-il possible d'ajouter un fichier du type stack.c externe à malib si je souhaite faire usage d'une pile de données?

Je me pose cette question afin de savoir si seuls les fichiers demandés doivent être inclus dans le répertoire.

Merci.

**Comment by Rehouma63** [comment]
Bonjour, 
je pense que tu dois essayer de garder ça simple. En rajoutant des fichiers qui sont pas demandés, tu risques de compliquer
la compilation.
Bonne chance.

**Comment by guyfrancoeur** [comment]
Bonjour,

Si tu veux faire cela je te demande de le faire avec les noms de fichiers de l'enoncé.  En résumé `stack.c` ne sera pas dans `stack.c` mais dans `malib.c`.

Je crois que la simplicité sera maintenu de cette facon.

G

**Comment by BassemNasralla** [comment]
le prof a dit le fois précédente que malib est à toi de gerer et c'est marqué dans l'énoncé les noms des fichiers que ton dépôt doit contenir donc je te propose de garder ça simple et suivre l'énoncé
