### ISSUE TITLE
TP2 : la fonction main() et rien d'autres

### ISSUE THREAD

**Issue by EzzeddineAlimi** [guyfrancoeur/INF3135_A2020#47]
Est ce qu'on sera pénalisé si on écrit tout le programme dans main() ?

**Comment by Jeremie-Gour** [comment]
C'est quand même une bonne pratique de découper ton code en fonctions et de refactoriser lorsque possible. Je ne sais pas si tu seras pénalisé si tu ne le fais pas, mais c'est généralement fortement recommandé et c'est une bonne habitude à prendre pour ton futur de programmeur. Donc p-e pas pénalisé sur les points, mais certainement sur d'autres niveaux!

**Comment by guyfrancoeur** [comment]
Bonjour,

Excellente remaque de Monsieur Gour. 👍 pile poile.
Aussi relire l'énoncé en cas de doute.

G
