### ISSUE TITLE
TP2 : question sur la transaction de sortie

### ISSUE THREAD

**Issue by louizette** [guyfrancoeur/INF3135_A2020#48]
Bonjour, pourquoi en transaction de sortie 23: il y'a 23 0 0 0 et pas 23 1 0 0    ?
alors qu'en entrée on a une erreur:    2001 01 **ERREUR**

merci d'avance.

**Comment by davidadjele** [comment]
bonjour @louizette , pour répondre à ta question je te suggère de bien relire cette partie de l'énoncé:

```
Si un capteur donne le mot ERREUR, vous devez réagir à la troisième manifestation du mot ERREUR;
- Vous ajoutez un (1) au compteur cumul des mots ERREUR par type;
- voir transaction 23.

```

**Comment by louizette** [comment]
ah oui à la 3ème erreur. merci

**Comment by bcote9005** [comment]
Merci du rappel! 👍
