### ISSUE TITLE
TP2: getVersion

### ISSUE THREAD

**Issue by Nana-Ousmane** [guyfrancoeur/INF3135_A2020#49]
Bonjour
J'ai ce message d'erreur qui bloque la compilation de mon programme : 

/usr/bin/ld: /tmp/ccAIQXzG.o: in function `main':
tp2.c:(.text+0x36): undefined reference to `getVersion'
collect2: error: ld returned 1 exit status

J'ai pas mal tout tenté  ce que je sais mais je ne peux pas solutionner ça et ça me ralenti.

Merci d'avance

**Comment by guyfrancoeur** [comment]
Allo,

Il manque qqc dans ton programme.  D'ou vient cette fonction ?
Si tu as besoin viens dans wsc.

**Comment by opdelta** [comment]
Ton tp2.c ne reconnaît pas la méthode getVersion.

Pose toi la question suivante: Où se trouve la méthode getVersion et comment je peux l'inclure dans ma compilation?


Ca devrait aider.

**Comment by Nana-Ousmane** [comment]
Bonjour,

Merci pour votre réponse. J'avais modifié la ligne de compilation pour tester que mon malib fonctionne. J'ai oublié de rajouter le tcv.o . Le problème est resolu. Merci beaucoup.

Ce tp est peut etre dur, mais au moins ça revèle à quel point je laisse des choses au hasard. lol

Bonne soirée
________________________________
De : opdelta <notifications@github.com>
Envoyé : 17 novembre 2020 21:04
À : guyfrancoeur/INF3135_A2020 <INF3135_A2020@noreply.github.com>
Cc : Ousmane Douah, Nana <ousmane_douah.nana@courrier.uqam.ca>; Author <author@noreply.github.com>
Objet : Re: [guyfrancoeur/INF3135_A2020] TP2: getVersion (#49)


Ton tp2.c ne reconnaît pas la méthode getVersion.

Pose toi la question suivante: Où se trouve la méthode getVersion et comment je peux l'inclure dans ma compilation?

Ca devrait aider.
