### ISSUE TITLE
TPx : size_t

### ISSUE THREAD

**Issue by Rehouma63** [guyfrancoeur/INF3135_A2020#50]
Bonjour, j'aurai une question conçernant le tp2:

Le size_t dans les signatures de transactions fait référence à quoi ? Doit-on s'en servir pour gérer les transactions en entrées et les transactions de sortie ?

Merci.

**Comment by husseinnahle** [comment]
On l'a vu dans le chapitre 6 structures de données. C'est un type de données qui représente la taille d'un objet en bit.(unsigned long long)
Et je pense qu'on doit l'utiliser, puisque les types sont précisés dans l'énoncer.

**Comment by Rehouma63** [comment]
Je vais aller voir ça, merci !

**Comment by guyfrancoeur** [comment]
Bonjour,

Petit rappel amical, ce type de demandes va à l'encontre :

 - des directives de l'énoncé;
 - du plan de cours;
 - de l'entente d'évaluation;

G
