### ISSUE TITLE
TP2 : Moyennes pour TH TA pulsation

### ISSUE THREAD

**Issue by EzzeddineAlimi** [guyfrancoeur/INF3135_A2020#51]
Bonjour,

si par exemple les données pour les degres étaient tous des ERREUR, la valeur affichée dans 21 sera 0 0 0 ? 
est ce que si la reponse est: 21 -nan -nan -nan est affiché est ce que c'est acceptable ?

merci

**Comment by tq3636** [comment]
Je ferais une réflexion sur la signification des -nan et j'agirais en conséquence.

En espérant que ma réponse flou aide un peu. :)

**Comment by louizette** [comment]
ca doit afficher des 0

**Comment by husseinnahle** [comment]
0 peut aussi représenter la moyenne des températures en degrés Celsius ... Mais en tout cas je ne pense pas qu'on doit afficher un `-nan` (not a number),  puisque sa représente une valeur indéfinie, ie une erreur de calcul comme 0 divisé par 0.

**Comment by guyfrancoeur** [comment]
Bonjour,

Voir #54
