### ISSUE TITLE
TP2 : Moyennes (connaissances générales, je voulais en savoir plus)

### ISSUE THREAD

**Issue by IssakhaW** [guyfrancoeur/INF3135_A2020#52]
Bonjour,

Je me demandais si la moyenne concerne les entrées d'un seul utilisateur ou de plusieurs.

Merci.

**Comment by maxowell** [comment]
Selon mon interprétation, les mesures prises par les puces concernent toujours le même utilisateur, sauf pour la transaction 04 où la puce reçoit le signal d'un autre utilisateur (On ne calcule pas la moyenne des signaux).

**Comment by olivier-bouchard-uqam** [comment]
Même chose pour mon interprétation, une série de transaction est passée à ton programme, et c'est sur ceux-ci que tu vas faire tes moyennes. Une fois toutes les transactions traitées on ne conserve pas les valeurs.

Bonne chance!

**Comment by poulayyy** [comment]
Il n'est pas mentionné le contraire dans l'énoncé, donc je crois bien que c'est seulement l'émetteur courant.

**Comment by IssakhaW** [comment]
@maxowell @olivier-bouchard-uqam @poulayyy  Merci pour vos retours.

**Comment by LikensonD** [comment]
La moyenne (transaction 21) , c est la moyenne des donnée reçu en entrée (TH, TA, pulsation) dans les transactions 01, 02, 03. Si ton capteur de pulsation  envoie des données x fois, tu dois aficher la moyenne  dans la transaction 21.

**Comment by guyfrancoeur** [comment]
Bonjour,

Il s'agit d'informations biométriques qui concernent le propriétaire de la puce.  Dans un but d'un suivit de votre santé et diagnostic de potentielles complications de santé.

Légèrement hors sujet pour ce tp.

G
