### ISSUE TITLE
TP2: Sortie (Attention à ce type de demandes)

### ISSUE THREAD

**Issue by EzzeddineAlimi** [guyfrancoeur/INF3135_A2020#54]
Pour l'exemple donné, on a  `2001 01 ERREUR` comme entree.

On aura `23 1 0 0` au lieu de `23 0 0 0` non ?

**Comment by poulayyy** [comment]
relis bien l'énoncé

**Comment by EzzeddineAlimi** [comment]
Je comprends toujours pas.

On a 23: Cumul des mots ERREUR pour TH TA pulsation

Définition : 23 `<cumul pour TH> <cumul pour TA> <cumul pour pulsations>`
et `2001 01 ERREUR` c'est TH.

**Comment by guyfrancoeur** [comment]
Bonjour,

Je crois que tu dois relire l'énoncé du tp, peut-être l'imprimer et lire le lien en bas.

Je demande aussi de ne plus faire de demande de solution ou des appels à tous pour savoir comment procéder.
Les travaux sont à faire individuellement.

Mettre une pression inutile sur le reste du groupe en utilisant le mot `je ne comprends pas` n'est pas acceptable.
Vous êtes responsable de vos études et de ce travail.

Consulter l'article suivant : [méthode pour comprendre un énoncé](https://www.phosphore.com/tout-pour-le-bac/methodo/fiches-methodes/bac-2020-comprendre-un-enonce/)

Cordialement,

G

**Comment by guyfrancoeur** [comment]
Bonjour,

Petit rappel amical, ce type de demandes va à l'encontre : 
- des directives de l'énoncé;
- du plan de cours;
- de l'entente d'évaluation;

G
