### ISSUE TITLE
TP2 : Transaction 00

### ISSUE THREAD

**Issue by LikensonD** [guyfrancoeur/INF3135_A2020#55]
Bonjour tout le monde, j ai une question concernant la transaction 00. 
Juste pour être sur, si je ne reçois pas la transaction 00 en entrée, est ce que je dois avoir la transaction 10 en sortie pareil?
Si oui,  j'aimerais savoir si ca se fait de façon instantanée (quel timestamp) ? 
Je suppose que la transaction 10 est indispensable pour la pastille réceptrice.

**Comment by PedroLuisBernardos** [comment]
Pour continuer avec ta question, j'aimerais demander `qu'est-ce qui arrive si la puissance n'est pas 2, 3 ou 4 ?` 

Moi je crois que la transaction 00 n'est pas indispensable (c'est pour ça que Guy nous donne les valeurs par défaut). Et pour le timestamp je mettrais `0` vu que c'est techniquement la première instruction du programme. Mais je n'ai pas de réponse précise.

**Comment by LikensonD** [comment]
@PedroLuisBernardos je pense que t as pas à t'inquiéter pour la puissance. 
Puissance de l'émetteur BT est : N = { 2, 3, 4 }
D'après moi les pastilles ne peuvent avoir que un de ces 3 puissance, alors il est logiquement impossible de recevoir une puissance autre que ces 3 là.

**Comment by obohigas708** [comment]
Bien relire la description de la transaction 00. Je crois qu'on peut déduire une réponse avec des éléments qui s'y trouvent.
