### ISSUE TITLE
TP2 : Timestamp (oh la la, attention)

### ISSUE THREAD

**Issue by maxowell** [guyfrancoeur/INF3135_A2020#56]
Bonjour, 
Je me rappelle qu'on avait discuté que si le timestamp d'une transaction était inférieur au timestamp de la transaction précédente (pas en ordre croissant), notre programme devait réagir.
Cependant, je ne vois pas dans l'énoncé un endroit qui indique de quelle façon réagir. 
Faut-il effectivement réagir pour cette situation ou est-ce moi qui a imaginé tout cela?
Merci!

**Comment by LikensonD** [comment]
Le prof avait dit pas pour le tp2

**Comment by JulesHauchecorne** [comment]
Je pense que on est supposé l'ignorer si un transaction n'est pas en ordre.

**Comment by Ibrahim-Davieau** [comment]
Bonjour, le prof avait dit qu'il n'y aurait pas d'erreur au niveau des transactions en entrée pour le Tp2 .

**Comment by louizette** [comment]
donc on a pas pas a gérer les timestamps pour tp2

**Comment by guillaumetb** [comment]
Je ferais attention à cette interprétation. Dans ce cas de figure la transaction n'est pas intrinsèquement invalide.

**Comment by guyfrancoeur** [comment]
Bonjour,

Tous les 👎 sont dans l'erreur.

Toujours faire attention avec les gens qui disent n'importe quoi.  ils veulent surement pas votre bien.
Vous devez traiter tous ce que vous êtes en mesure de traiter en fonction du temps, des obligations et des requis
mais aussi en fonction des vos propres intuissions * connaissances * energies = R .  
Lors de la correction vous allez savoir si vous avez pris la bonne décision.
 
Le timestamp a été mainte fois dit et redit. Vous devez le (les) gérer.  Je ne sais plus comment le dire.

Je vous fait confiance pour prendre la bonne décision.  On lâche pas. vous êtes capable.

G

**Comment by poulayyy** [comment]
@guyfrancoeur ,
si ce point à été mainte fois dit et redit et qu'il y a encore des questions à ce sujet, est ce qu'il serait mieux d'ajouter cette particularité dans l'énoncé ? 

Merci !

**Comment by Nana-Ousmane** [comment]
Je suis d'accord avec @poulayyy

**Comment by guyfrancoeur** [comment]
Bonjour,

Je vais ajouter ceci est-ce normal de traiter les transactions temporelles dans le désordre ?
Même sans avoir suivit des cours d'informatique je suis persuadé que nous pouvons répondre.

Peut-être pas toujours, mais des fois oui. Voici des cas similaires au nôtre qui mérite une réflexion :

Cas 1 : Avion

Nous avons un avion : 
 - au temps 1, il est sur la piste;
 - au temps 1000, il est dans les airs;
 - au temps 10000, il vient d'atterrir;

Je suis dans le vol et les instruments ont reçu les infos temps 1 à 75, puis rien. Aussi recu les temps 8000 à 9000 (décente), et soudainement nous avons les données du temps 1000 à 3000.

Disons que je suis à 100 mètres au moment de la réception de la transaction 9000. À la transaction 1000 l'altitude de  l'avion est à 2000 mètres que dois-je faire ?  Que dois-je dire au pilot monter ? Descendre de 2000 mètres ?


Cas 2 : Les turbines dans un barrage.

Je dois savoir si oui ou non je dois fermer (arrêter) une turbine alternateur à un moment de fonctionnement incorrect.  Pour ce faire je vais recevoir les données, des streams de données. Beaucoup, comme dans votre cas.
Si je ne suis pas en mesure de recevoir les données et de les traiter vite et bien lors d'une surchauffe par exemple, il ne sert a rien de recevoir les informations bien trop tard pour agir correctement.  L'équipement est deja détruit, des millions de dollars dans le feu.

Le fait de recevoir les informations dans le désordre cause des problèmes pour les ordinateurs, car ils ne savent pas comment réagir. Est-ce bon ou est-ce une erreur?

Le fait de mettre un timestamp indique que nous voulons nécessairement traiter ce cas.

Cas 3: streams, transfert (voix, fichier)

Nous avons fichier à envoyer à un ami.  Les paquets sont dans un ordre précis.  Tentez svp de reconstruire un fichier ou les paquets sont dans un ordre incorrect que faire.  Avec de la voix par exemple.  Comment devons-nous procéder ?  Si les paquets arrivent trop tard (délais) que faire? On attend combien de temps afin de faire l'ordonnancement ?

Cas 4 : nous sommes sur une mission de sauvetage

Les informations sur les conditions climatique ne sont pas arrivées à temps ou dans le bon ordre pour finaliser le sauvatage de centaines de personnes sur le mont Blanc, que dois-je faire? Puis-je retourner dans le temps pour reprendre une décision? Ce n'est pas toujours possible.

Si ce cas ou ce genre de cas vous trouble, laissez-le de côté pour le moment continué sur autre chose.

Je vous demande de rester concentré et de ne pas laisser vos émotions prendre le contrôle de votre esprit.

Dans ce cours nous devons réfléchir, prendre des décisions.  Vous avez les vôtres (décisions à prendre en toute liberté) et j'ai les miennes. Bravo pour vos prises de position, mais nous ne sommes pas dans un cours de politique, mais d'informatique.  La COVID n'excuse pas tout.

G
