### ISSUE TITLE
TP2 : Exécution du programme ./tp2

### ISSUE THREAD

**Issue by edanbanane** [guyfrancoeur/INF3135_A2020#57]
Bonjour, c'est écrit dans l'énoncé qu'on peut lancer le programme avec la commande ./tp2, cela veut dire qu'on a aucune donnée en entrée dans ce cas et qu'il faut réagir en conséquence si je comprends bien ?

**Comment by JulesHauchecorne** [comment]
Je pense que c'est pour s'assurer que le programme fonctionne même sans transactions et que ça ne cause pas d'erreurs.

**Comment by guyfrancoeur** [comment]
Bonjour,

La question qu'il faut se poser ici c'est : mon programme accepte les trx de quelle façon ?

et ma réponse à la question précédente correspond à quoi ?

G

**Comment by poulayyy** [comment]
hgfdjg

**Comment by PierreOlivierBrillant** [comment]
@guyfrancoeur qu'est-ce que tu voulais dire par "trx"?

**Comment by louizette** [comment]
@PierreOlivierBrillant  transactions
