### ISSUE TITLE
Attention aux TP de dernière minute

### ISSUE THREAD

**Issue by PierreOlivierBrillant** [guyfrancoeur/INF3135_A2020#60]
Selon météomédia, il pourrait y avoir du verglas cette nuit, pouvant provoquer des pannes de courant. Il serait judicieux de pousser votre code souvent afin d'éviter d'être mal prit avec une remise de dernière minute.

Source: [meteomedia.com](https://www.meteomedia.com/ca/alertes/high-alerte/quebec/montreal)

**Comment by Rehouma63** [comment]
Au pire on peut faire un hotspot avec la LTE 😆

**Comment by PierreOlivierBrillant** [comment]
> Au pire on peut faire un hotspot avec la LTE laughing

Bien pensé! Mais certains n'ont que des tours!

**Comment by Patrickcob** [comment]
Météomédia c'est du hasard!
