### ISSUE TITLE
java.labunix.uqam.ca

### ISSUE THREAD

**Issue by bdkandil** [guyfrancoeur/INF3135_A2020#61]
Salut Les Amis,

Je n'arrête pas d'avoir des problèmes de connexions sur le serveur, il déconnecte souvent. Je n'arrive plus du tout en ce moment.

Est ce que d'autres ont eu des problèmes?

Bon courage à tous
DK

**Comment by TarekElTayeh** [comment]
Tout va bien de mon cote. Comme solution, tu pourrais essayer de te connnecter sur les serveurs de l'UQAM via FileZilla si PUTTY ne fonctionne toujours pas !

Bonne chance !

**Comment by PierreOlivierBrillant** [comment]
Sinon dans git bash tu peux toujours essayer avec ssh code-ad@java.labunix.uqam.ca

**Comment by fialiayoub** [comment]
Essaye de te connecter via le terminal avec "ssh" pour voir si ça fait encore les mêmes problèmes de connexions. Perso moi y'a pas de soucis de se coté là.

**Comment by PierreOlivierBrillant** [comment]
> Essaye de te connecter via le terminal avec "ssh" pour voir si ça fait encore les mêmes problèmes de connexions. Perso moi y'a pas de soucis de se coté là.

Si je me souviens bien, ssh est seulement sur linux ou git bash, donc si c'est fait sur windows il faut faire attention dans quel terminal on essaie d'exécuter la commande.

**Comment by louizette** [comment]
peut tu as un problème de connexion internet.

**Comment by durgeta** [comment]
@PierreOlivierBrillant : un client `OpenSSH` est disponible sur Windows 10 depuis plusieurs mois, les outils SSH (notamment pour les clés) ne sont pas tous présent mais le client en lui même fonctionne très bien dans `cmd.exe` ou dans `powershell`.

Vous vous connectez comment au serveur `java` sans passer par SSH ? 🤔

Mais bref, pour répondre à @bdkandil : j'ai aussi des soucis avec la connexion au serveur (je passe uniquement en SSH perso), mais surtout à cause d'une bonne grosse latence que je n'avais pas il y a quelques semaines. Généralement j'ai l'impression que ça vient plutôt de ma connexion à la maison : quand je passe en partage de connexion avec mon téléphone ça marche mieux. Mais la latence reste parfois présente et parfois aussi des déconnexions intempestives :/ J'ai pas encore réussi à bien identifier le soucis, mais globalement il y a bien plus de chance que ça soit un problème local, donc chez toi, et pas à cause du serveur.

Si tu as d'autres moyens de te connecter au serveur / d'autres FAI à disponibilité, essaye les tous pour voir si ça règle ton problème 🧐 A suivre...

**Comment by guyfrancoeur** [comment]
Bonjour,

Avez-vous attendu à la dernier minute pour livrer ?  Oh.  On en reparle en classe pour ssh.

G
