### ISSUE TITLE
TP3: énonce

### ISSUE THREAD

**Issue by Nana-Ousmane** [guyfrancoeur/INF3135_A2020#65]
J'ai de la misère à comprendre ce bout de l'énoncé. Pourriez vous clarifier un peu plus svp?

<<La note zéro est attribuée si :
vous utilisez .. avec la commande cd;
vous utilisez .. ou * avec la commande rm;
vous descendez, dans la structure, en deçà de votre répertoire de travail;>>

Merci d'avance

**Comment by JulesHauchecorne** [comment]
En théorie c'est simple, fait aucune manipulation relative à ton répertoire qui nécessite ..   ( en gros sortir du ton projet)  . Ça ne devrait pas être un problème puisque tout tes fichiers devraient être dans le même repertoire et juste data/ devrait être un dossier mais il est dans le projet pas à l'extérieur.

**Comment by Nana-Ousmane** [comment]
d'accord merci Jules
