### ISSUE TITLE
TP3 : Sortie du TP3 est-elle incrémentale du tp2 ?

### ISSUE THREAD

**Issue by MaelPJoly** [guyfrancoeur/INF3135_A2020#66]
Bonjour,

Il est dit que  "Le tp3 ajoute une fonctionnalité qui compte de nombre de lignes lues et selon le cas affichera les informations recueillies.".

Est-ce que le tp3 doit aussi afficher ce que le tp2 affichait (c'est à dire les transactions 10, 14,15, 21, 22 et 23) et ensuite afficher les informations détaillées, ou bien le tp3 n'affiche que les informations détaillés sur les transaction.

Merci.

**Comment by patlenew** [comment]
Techniquement le tp3 reprend le tp2 et ajoute des modifications, donc comme expliqué dans l'énoncé, il peut possiblement affiché les mêmes choses que le tp2, ou non, dépendamment des options
