### ISSUE TITLE
TP3 : Option -d : clarification

### ISSUE THREAD

**Issue by davidadjele** [guyfrancoeur/INF3135_A2020#67]
Bonjour,
J’ai une question en lien avec l’option `-d` qui permet d’afficher le nombre de transactions pour chacun des types de transactions.
En regardant l’exemple de sortie donné dans l’énoncé pour cette option (information detaillee), il n’y a de transaction 00. Je me suis dit c'est sûrement parce que le programme n'a pas reçu de transaction 00.
Doit-on alors considerer que si le nombre de transaction pour un type de transactions est égale à 0, on ne l'affiche pas?

Merci d'avance.

**Comment by guyfrancoeur** [comment]
Bonjour,

Il n'y a pas de détail pour la transaction 00, de mémoire.  En d'autres mots il n'y a pas de 00 affiché avec l'option -d.

**Comment by davidadjele** [comment]
Parfait et merci.

**Comment by louizette** [comment]
@guyfrancoeur  mais dans les autres options on considère la transaction 00 ?

**Comment by guyfrancoeur** [comment]
Allo,

Oui simplement on ne l'affiche pas.

G
