### ISSUE TITLE
TP3 : Pour les trx non reconnues.

### ISSUE THREAD

**Issue by JulesHauchecorne** [guyfrancoeur/INF3135_A2020#71]

**Comment by JulesHauchecorne** [comment]
est ce que c'est juste si le num de transaction est à l'extèrieur de celles reconnues ou ça inclut les transactions qui avaient des erreurs de validations.

**Comment by Nana-Ousmane** [comment]
Une trx non reconnue c'est en effet une trx non citée dans l'enoncé . Ça n'inclut pas les trx invalides qui elles sont reconnues.

**Comment by guyfrancoeur** [comment]
Bonjour,

Veuillez fournir des exemples pour décrire vos cas svp ..
