### ISSUE TITLE
Champ d'une Transaction manquant

### ISSUE THREAD

**Issue by Jrobill4rd** [guyfrancoeur/INF3135_A2020#72]
Je crois que la question à déjà été adressée mais je ne trouve plus le issue.

Si en entré nous recevons exemple : 1000 01 (TH manquant)

Deux questions : 
1. Comment doit-on le gérer? On l'ignore?
2. Est-ce qu'on doit le rajouter au compteur de transaction non reconnu ? Invalide?

**Comment by saledemon** [comment]
J'ai déjà posé la question en effet lors du TP2. On m'avait répondu qu'on ne devait pas le prendre en compte puisque la pastille n'enverrait pas de telles transactions.

Mais ceci dit, dans le TP3 il y a un compteur de trx non reconnues, donc à voir... peut-être l'inclure là-dedans.

**Comment by Jrobill4rd** [comment]
Ah ça fait du sens! Je vais attendre la reaction de Guy à ton commentaire. Merci beaucoup.

**Comment by guyfrancoeur** [comment]
Bonjour,

@saledemon et les autres : 
Attention, Ceci était vrai pour le tp2.  Maintenant nous sommes dans le tp3.
Je crois que vous êtes en mesure de traiter ce cas sans trop de changements ou difficulté.

@Jrobill4rd 

- La trx est reconnue.
 - Les données ne sont pas valides.

G

**Comment by Jrobill4rd** [comment]
Merci beaucoup c'est bien ce que je pensais !
