### ISSUE TITLE
TP3 : Signature des commandes

### ISSUE THREAD

**Issue by nickthivierge** [guyfrancoeur/INF3135_A2020#73]
Bonjour, j'aimerai savoir si nous sommes autorisé à choisir le type et le nombre de paramètre que doit prendre la fonction cmd ou doit-on absolument y aller avec un nombre indéterminé(...)? Est-ce que la valeur de retour doit également être un int ou la signature de la fonction est plutôt à titre de suggestion?

**Comment by nineyalexandre** [comment]
Bonjours Nicolas,

Si on se réfère à l'énoncé, le nombre d'arguments ainsi que leur type est laissé à l'analyse de l'étudiant: 
`Le code source de la fonction int cmd(...)`
Concernant le type de la valeur de retour, elle sera systématiquement dans la signature de la fonction. A titre de comparaison et d'éclaircissement, tu peux néanmoins analyser la fonction main().

**Comment by guyfrancoeur** [comment]
Allo,

La fonction  cmd(), sa signature, son retour et son contenue est au choix du développeur.

G
