### ISSUE TITLE
TP3: Contenu du fichier outil3.c

### ISSUE THREAD

**Issue by PedroLuisBernardos** [guyfrancoeur/INF3135_A2020#74]
Allo!
Je me demandais si dans le but de respecter la limite de 199 lignes du fichier `malib.c` on pouvait déplacer des fx de malib vers outil3?

Il est écrit que outil3.c doit:

```
Ce que vous devez retrouver dans le fichier outil3.h et outil3.c:

Ce module est indépendant;
Aucune dépendance sur des librairies personnelles ou non standard au langage C;
Le code source de la fonction float distance(int _signal, int _power);
La fonction gère le calcul de la distance en mètres;
Le code source de la fonction int cmd(...);
La fonction gère les arguments de la ligne de commande;
La MACRO _OUTIL3_H_ doit exister pour la détection des inclusions multiple;
Limiter le code source à 99 lignes ou moins, une instruction par ligne.
```

Mais rien ne dit qu'on ne peut pas en avoir d'autres.

Je voulais juste confirmer avec @guyfrancoeur  pour être certain de ne pas perdre des points si je fais ce changement.

Merci!

**Comment by Nana-Ousmane** [comment]
Si je me fie à l'énoncé , outil3 doit contenir "distance" et "cmd", il n'est jamais dit qu'elle doit contenir UNIQUEMENT ces derniers.  De plus si elle ne doit contenir aucune dépendances,  y'a pas 36 façon de procéder. conclusion...

**Comment by guyfrancoeur** [comment]
Bonjour,

Je confirme : vous pouvez ajouter des fonctions en plus des deux mentionnées dans `outil3`.

G

Réagissez.
