### ISSUE TITLE
TP3 : Trx valides

### ISSUE THREAD

**Issue by Rehouma63** [guyfrancoeur/INF3135_A2020#78]
bonjour,
est-ce qu'une transaction avec le mot ERREUR ou une valeur invalide (par exemple Température humaine inférieure à17.0C)
est quand même considérer comme valide ? 
Ex: 
2 01 38.2
2001 01 ERREUR

**Comment by Nana-Ousmane** [comment]
trx avec le mot erreur c'est une  trx dont la valeur n'est meme pas numérique. 
trx invalide c'est une valeur numérique mais dont la fonction de validation retourne false (donc hors de l'intervalle de validation). 
trx valide c'est tout ce qui n'est ni invalide ni en erreur.
trx non reconnu c'est une trx dont le TIMESTAMP n'est pas reconnu. rien à voir avec la valeur .

**Comment by Rehouma63** [comment]
ta dis le contraire dans ce [issue](https://github.com/guyfrancoeur/INF3135_A2020/issues/71). Et dans l'énoncé, pour l'option -i, il y a seulement 2 cas où la transaction est invalide, à savoir Lorsqu'un code de transaction n'est reconnu ou Lorsque le timestamp est inférieur au temps précédent. Donc je présume que même si les valeurs sont incorrectes ou s'il y a  le mot erreur, elle sont valides tant que le timestamp et le code de transaction sont corrects.

**Comment by Nana-Ousmane** [comment]
Je ne suis pas sur de te suivre. Je crois que tu confond les termes "valide/invalide" et "reconnue/non-reconnue". 
Je n'ai pas l'impression que ce que j'ai dit dans l'autre issue soit en contradiction avec ce que je dis ici.

Pour pas t'embrouiller davantage je laisse @guyfrancoeur te repondre.

**Comment by louizette** [comment]
@Nana-Ousmane  valeur non reconnu c'est celle qui a le code de transaction différent des 00 01 02 03 04 05

**Comment by Nana-Ousmane** [comment]
Oui exact @louizette
