### ISSUE TITLE
liste.sh

### ISSUE THREAD

**Issue by saledemon** [guyfrancoeur/INF3135_A2020#8]
Bonjour,
Est-ce que le script liste.sh doit rouler lorsqu'on entre la commande 'make test', lorsqu'on entre './tp1' ou lorsqu'on entre './liste.sh' ? C'est-à-dire, est-ce que c'est à l'intérieur du fichier tp1.c qu'on doit intégrer le script ou on peut seulement rediriger le output de './tp1' vers l'entrée standard de liste.sh au travers de la cible 'make test' ?

Aussi, je me demandais si on avait une idée de combien de tests doivent passer ou non ? Comment est-ce qu'on fait pour évaluer si nos tests sont corrects ?

**Comment by guyfrancoeur** [comment]
Bonjour,

Merci beaucoup pour tes questions @saledemon .

Nous ne voulons aucune dépendance entre les programmes.  Enfin pas directement.

Combien de tests passent : difficile de savoir avant, ce n'est pas le but des tests ? 

Comment évaluer mes tests : comme vu en inf2120 ou inf2050.  Jeux d'essai, évaluation du code (code review), programme automatique de révision. Création de fonctions similaires (en fonction des spécifications) + lancement sur ces fonctions.

Mais simplement : Principe du programmeur C : 
- Le programmeur C
  + est censé savoir ce qu'il fait. (sinon il ne fait pas).
  + ne laisse rien au hasard.
  + ne prend pas de décision qui puisse nuire à la vie humaine.

G
