### ISSUE TITLE
Make clean

### ISSUE THREAD

**Issue by NicolasGuay** [guyfrancoeur/INF3135_A2020#9]
"Lorsqu'on entre make clean, le projet revient dans son état d'origine, c'est-à-dire son état lors de la récupération initiale, ou le strict nécessaire;"
Désolé, mais je trouve cette phrase ambiguë.
L'état lors de la récupération initiale sous-entend qu'il faut supprimer les fichiers téléchargés après le clonage du dépôt (i.e tcv.h et tcv.o). Cependant le strict nécessaire sous-entend qu'il ne faut pas supprimer les fichiers tcv.h et tcv.o puisque la compilation est impossible sans ces fichiers.
Je vous demande donc s'il faut supprimer les fichiers tcv ou non avec l'option make clean.
Merci et bonne fin de semaine!

**Comment by saledemon** [comment]
Oui il faut les supprimer, car avec la commande 'make lib', on peut télécharger ces fichiers à nouveau. À chaque build, les fichiers sont téléchargés (pour qu'ils soient à jour)

**Comment by guyfrancoeur** [comment]
Merci @saledemon,

Belle contribution. Néanmoins attention aux réponses, trop directes.
@NicolasGuay : l'ambigüité est relative, certain trouve ça clair d'autre moins.

État d'origine c'est en d'autres mots tes fichiers. Est-il possible de récupérer `tcv.h` et `tcv.o` a n'importe quel moment du jour ou de la nuit ?

G

**Comment by NicolasGuay** [comment]
Ok merci pour la précision:)
